- hosts: localhost
  
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  
  vars_files:
    - example.config.yml

  pre_tasks:
  - name: Include main playbook configuration.
    ansible.builtin.include_vars: "{{ item }}"
    with_fileglob:
      - "{{ playbook_dir }}/config.yml"
    tags: ["always"]
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/fonts.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/node.yml
    - import_tasks: tasks/npm-packages.yml
    - import_tasks: tasks/nvim.yml
    - import_tasks: tasks/brave.yml
    - import_tasks: tasks/dotfiles.yml
