- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/git-setup.yml
    - import_tasks: tasks/core-setup.yml
    - name: Setup zsh
      import_role:
        name: ansible-role-zsh
      vars:
        zsh_user: camiloavelar
    - name: Setup node
      import_role:
        name: ansible-role-nvm
      become: true
      become_user: camiloavelar
    - import_tasks: tasks/npm-packages.yml
