---
- name: Install apt repositories.
  tags: &apt_tags ['install', 'apt']
  become: true
  ansible.builtin.apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: true
  loop: "{{ apt_repositories }}"
  when:
    - apt_repositories is defined
    - apt_repositories is iterable
    - apt_repositories | length > 0

- name: Install apt packages.
  tags: *apt_tags
  become: true
  ansible.builtin.apt:
    name: "{{ item.name | default(item) }}"
    autoclean: true
    autoremove: true
    update_cache: true
    state: latest
  loop: "{{ apt_packages }}"
  register: install_result
  when: apt_packages is defined

- name: Clean apt cache.
  become: true
  ansible.builtin.command: >
    apt clean && apt autoremove && apt autoclean
  when: apt_packages is defined and not install_result.skipped
