---
- name: Install global Pip Packages.
  tags: pip
  ansible.builtin.pip:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    version: "{{ item.version | default(omit) }}"
    executable: "{{ item.executable | default('pip3') }}"
    extra_args: "{{ item.extra_args | default(omit) }}"

  loop: "{{ pip_packages  }}"
  loop_control:
    label: "{{ item.name }}"
  when: pip_packages is defined
